# A unique id that identifies what this task is based on.
#
# Do not touch!!!
TaskID: FastMathTask

# The task name
Name: Fast math

# The task duration in seconds
Duration: 7

# The game-mode players are set to when the task begins.
GameMode: adventure

# Whether should the question include adding questions
#
# For example, "8 + 12"
AddingQuestions: true

# Whether should the question include adding questions
#
# For example, "12 - 5"
SubtractingQuestions: true

# Whether should the question include multiplying questions
#
# For example, "7 * 8"
MultiplyingQuestions: true

# Whether should the question include division questions
#
# For example, "60 / 5"
DivisionQuestions: true

# The minimum input (inclusive) that will be used in generating questions
#
# For example, if this is 5, then questions will never include any
# number less than 5.
MinimumInput: 2

# The maximum input (exclusive) that will be used in generating questions
#
# For example, if this is 15, then questions will never include any
# number greater than 14 (since 15 is exclusive).
MaximumInput: 13

# The possibilities per operation. This means how many questions
# should be generated per mathematical operation in every question-picking.
#
# If this is 5, then there will be 5 possibilities for adding,
# 5 possibilities for subtracting, 5 possibilities for multiplying
# and 5 possibilities for division.
#
# The higher this is, the more the randomness of the generated questions
# will be (hence becomes more unpredictable which is better).
PossibilitiesPerOperation: 5

Question: # How the question is broadcasted.

  # The message broadcasted to players
  Message: "&e四则运算: &b{question} &e?"

  # Where it is broadcasted. Can be either:
  #
  # 1. ActionBar: Through the action bar
  # 2. Title: Displays a title
  # 3. Subtitle: Displays a subtitle (smaller than title)
  # 4. Chat: Sent to players
  # 5. None: Does nothing
  #
  # Note: If you choose title or subtitle, you can add "FadeIn", "Display", "FadeOut"
  #       to customize titles.
  BroadcastBy: Subtitle

  # Properties to customize the title/subtitle.
  FadeIn: 0
  Display: 40
  FadeOut: 5

# Rewards settings
Rewards:

  # When are points rewarded. This has 2 values:
  #
  # 1. 'finished': All players who finish this task will be rewarded with the same
  #                amount of points regardless of who finished first.
  #                Must also define a 'Points' property with the amount of points
  #                given to each player.
  # 2. 'by_order': Players will be rewarded by the order in which finished first.
  #                Points given to players can be defined in the config.yml.
  #                Check the ArenaSettings -> RewardsByOrder
  When: by_order

  # The points given to players who finish this task. Only used if 'When' is set
  # to 'finished'.
  Points: 1

# How the task is broadcasted to players
Narration:

  # The message broadcasted to players
  Message: "&e快速计算!"

  # Where it is broadcasted. Can be either:
  #
  # 1. ActionBar: Through the action bar
  # 2. Title: Displays a title
  # 3. Subtitle: Displays a subtitle (smaller than title)
  # 4. Chat: Sent to players
  # 5. None: Does nothing
  #
  # Note: If you choose title or subtitle, you can add "FadeIn", "Display", "FadeOut"
  #       to customize titles.
  BroadcastBy: Title

  # Properties to customize the title/subtitle.
  FadeIn: 0
  Display: 40
  FadeOut: 5

# Is pvp allowed for players in this task.
#
# Note: When the player finishes the task, they can no longer
#       PvP other people.
AllowPvP: false

# Are players allowed to drop items in this task
#
# Note: When the player finishes the task, they can no longer
#       drop items.
AllowItemDropping: false

# Are players allowed to place blocks while doing the task
#
# Note: When the player finishes the task, they can no longer
#       place blocks.
AllowBlockPlacing: false

# Are players allowed break blocks while doing the task
#
# Note: When the player finishes the task, they can no longer
#       break blocks.
AllowBlockBreaking: false

# Whether should the plugin announce right after a player finishes
# (or fails in) the task.
AnnounceOnFinishOrFail: true

# Whether should the player's hotbar be shuffled when the
# task begins.
ShuffleHotbar: false

# Whether should the arena regenerate once the task is over.
RegenerateWhenFinished: false

# Whether should players be teleported back to their spawn-point once
# they finish the task.
TeleportBackToSpawnPointWhenFinished: false

# Items to give to players when the task starts
#
# Follows this template:
# - Type: apple
#   DisplayName: '&cApple'
#   Lore: 
#     - '&eThe legendary apple'
#   Slot: 0 <-- slot to give the item in
GiveItems: [ ]

# The "rubbish" in the inventory
#
# Rubbish is basically items that repeatedly will fill the entire inventory,
# with full stacks of 64.
#
# Specify the item types below, for example:
# Rubbish:
# - cookie
# which will fill the whole inventory with cookies.
Rubbish: [ ]
